name: OpenWrt Builds
on:
  push:
  watch:
    types: started
  schedule:
    - cron: "0 0 * * */3"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  X64:
    runs-on: ubuntu-latest
    name: Arch x64
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Copiler
      uses: Sirherobrine23/Actions-Build-Openwrt@main
      with:
        config: x64.config
        p2: p2.sh
        workdir: x64/

    - name: "Upload with tag: x64_${{ github.run_id }}"
      if: env.UPLOADTORELEASE == 'true'
      uses: softprops/action-gh-release@v1
      with:
        name: Generic X64 Build
        tag_name: "x64_${{ github.run_id }}"
        body_path: ${{ env.BODYFILE }}
        files: "${{ env.RELEASEFOLDER }}/*"

  wr941ndv3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - adblock
          - cli
          - luci
          - wireguard-luci
          - wireguard-cli
        branch:
          - openwrt-19.07
          - openwrt-18.06

    name: "Branch: ${{ matrix.branch }}, Config: ${{ matrix.config }}"
    steps:
    - name: Checkout Reposiory
      uses: actions/checkout@main

    - name: "Copiler Openwrt with config: ${{ matrix.config }}, and Branch: ${{ matrix.branch }}"
      uses: Sirherobrine23/Actions-Build-Openwrt@main
      continue-on-error: true
      with:
        config: "configs/${{ matrix.config }}.config"
        branch: "${{ matrix.branch }}"
        p2: p2.sh
        workdir: wr941nd_v3/
        namefiles: |
          ${{ matrix.branch }}
          ${{ matrix.config }}

    - name: "Upload with tag: WR941ND_v3-${{ github.run_id }}"
      if: env.UPLOADTORELEASE == 'true'
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: "TP-Link WR941NDv3, Branch: ${{ matrix.branch }}, Config: ${{ matrix.config }}"
        tag_name: "WR941ND_v3-${{ github.run_id }}"
        body_path: ${{ env.BODYFILE }}
        files: "${{ env.RELEASEFOLDER }}/*"
