name: OpenWrt Builds
on:
  push:
   workflow_dispatch:
     inputs:
       target:
         description: "Build target"
         required: true
         default: all
         type: choice
         options:
          - all
          # Here target copiler
          - Core
          - Aurora
          - Samaritan
          - Machine

 env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     - name: Copiler
       uses: Sirherobrine23/Actions-Build-Openwrt@main
       with:
        CONFIG: .config
        WORKDIR: Core/
 
     - name: "Upload with tag: Core_${{ github.run_id }}"
       if: env.UPLOADTORELEASE == 'true'
       uses: softprops/action-gh-release@v1
 
     - name: Copiler
       uses: Sirherobrine23/Actions-Build-Openwrt@main
       with:
        CONFIG: .config
        WORKDIR: Aurora/
 
     - name: "Upload with tag: Aurora_${{ github.run_id }}"
       if: env.UPLOADTORELEASE == 'true'
       uses: softprops/action-gh-release@v1
 
     - name: Copiler
       uses: Sirherobrine23/Actions-Build-Openwrt@main
       with:
        CONFIG: .config
        WORKDIR: Samaritan/
 
     - name: "Upload with tag: Samaritan_${{ github.run_id }}"
       if: env.UPLOADTORELEASE == 'true'
       uses: softprops/action-gh-release@v1
 
     - name: Copiler
       uses: Sirherobrine23/Actions-Build-Openwrt@main
       with:
        CONFIG: .config
        WORKDIR: Machine/
 
     - name: "Upload with tag: Machine_${{ github.run_id }}"
       if: env.UPLOADTORELEASE == 'true'
       uses: softprops/action-gh-release@v1
# Build openwrt
Build openwrt in Github CI/CD and release